### PR TITLE
Add templating support

### PR DESCRIPTION
**Pull request by mre**
This introduces a new `--template` option that can be
used to specify the path to a Tera template file.
This way, styling can be totally customized by the
user.
This required a better separation between the
"data aggregation" part and the "data representation"
part (the output) so some parts had to be moved around.

I added this feature because I'm using `github-star-counter` for my
homepage now and I needed custom formatting. 😊 [See here](https://endler.dev/about/).
Not sure if you like to merge this in; I could also maintain my own fork
if that's not something you would like to have in your repo.

### CODE REVIEW

**Comment by Byron** [comment]
Hi @mre , thanks a lot for contributing your changes :)!

I took a stroll on the website that uses it and liked the looks. Something I immediately tried to do is click on the repo names, but nothing happened. Maybe an avenue for improvement.

What prevents me from merging right away is the failing tests - it's just about a function that moved around to assert on the output it produces by default. Do you think it's worth it to attempt a fix?

Something I think could be useful, and thus is entirely optional, is to make the templating part of the library. That way, others could use it independently of the binary, which might even be useful for you eventually.

What are your thoughts?

**Review by Byron — CHANGES_REQUESTED** [review]
Just so I don't forget: tests should be fixed if there is the time, before a merge can happen. Thank you.

**Comment by mre** [comment]
Ah yeah, forgot the tests. I'll set myself a reminder to look into it next week. 😉

**Comment by mre** [comment]
As for the links to the repos, it would be great to have them in the `Repo` struct as well. I could certainly use them for my homepage. Maybe we should create another issue for that? (Or maybe there already is a way to print the links that I don't know of.)

**Comment by Byron** [comment]
Thanks, I am happy to hear that! In fact, this project just served as an async playground, and made it easy to learn how async changes the way one models complex concurrency graphs. Once this PR is merged, I would like to invite you to have write access to master, so you can adapt it more easily to your needs and play around with it according to your use cases. This would, for instance, allow you to (probably trivially) add URLs to the `Repo` struct, or whatever else you would need.
Bis dahin!

**Comment by mre** [comment]
At long last I got around to fixing the tests. @Byron please have another look. 😊

**Comment by Byron** [comment]
Thanks, @mre , works perfectly! I will cut a new release soon!

**Pull request merged**
